version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todo_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  redis:
    image: redis:7-alpine
    container_name: todo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todo-network

volumes:
  mysql_data:
  redis_data:

networks:
  todo-network:
    driver: bridge